language: c
sudo: required

services:
  - docker

env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
  - secure: "C3Gd8W9U0yQIxnUkcKlzicB2iOeZ42NPpVXTOnigjoc2UoI4eVYlDjEZjccZAIn0wHUguircvBt0eyLD7cuNf2mTozJ21BG0NpMdYbG1n/aVchnJBr6rldb2X3kVmQCj50LQKm+aINbK1qSs56VIUwNepPiul+HPMV6sL5sQ5M0="
  - ASAN_OPTIONS='halt_on_error=1'
  - UBSAN_OPTIONS='halt_on_error=1'

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages:
    - gcc binutils intltool
  # Coverity scan add-on, fires only when pushing to the `coverity_scan` branch
  coverity_scan:
    project:
      name: "sriemer/scanmem"
      description: "Build submitted via Travis CI"
    notification_email: s.parschauer@gmx.de
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make"
    branch_pattern: coverity_scan

script:
  - if [ "${COVERITY_SCAN_BRANCH}" == 1 ]; then exit ; fi
  - docker pull ubuntu:bionic
  # mount the project git directory to the container and
  # use it as working directory
  - docker run -t -d --name="bionic" -v /home/travis/build/${PROJECT_NAME}:/scanmem -w /scanmem ubuntu:bionic /bin/bash
  - docker ps
  - docker exec bionic /bin/sh -c "apt-get update && apt-get upgrade -y"
  - docker exec bionic /bin/sh -c "apt-get install -y git gcc binutils libtool intltool make libreadline-dev python"
  - docker exec bionic /bin/sh -c "gcc --version"
  - docker exec bionic /bin/bash -c "./autogen.sh && ./configure --enable-gui"
  - docker exec bionic /bin/bash -c "make CFLAGS='-O2 -fsanitize=address,undefined'"
  - docker exec bionic /bin/bash -c "make check VERBOSE=1"
